### ISSUE TITLE
Error with LessCompiler when sending reports via email - no reports are sent

### ISSUE THREAD

**Issue by willfurnell** [Icinga/icingaweb2-module-reporting#106]
## Describe the bug

When the scheduler tries to send a report by email via the scheduler and fails with the following error:

`ERROR: ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:210 with message: file_get_contents(): Filename cannot be empty`

## To Reproduce

1. Schedule a report
2. Run the scheduler via systemd service

## Expected behavior

An email is sent with the SLA report

## Screenshots

N/A

Stacktrace:

`ERROR: ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:210 with message: file_get_contents(): Filename cannot be empty`

## Your Environment

* Module version: Latest git master
* Dependent module versions: Latest git master
* Icinga Web 2 version and modules (System - About): 
<html><body>

icinga/icinga-php-library | 0.7.0
-- | --
icinga/icinga-php-thirdparty | 0.10.0

</body>
</html>
<html><body>

Name | Version
-- | --
aquilon | 1.0
idoreports | 0.9.1
incubator | 0.5.0
ipl | v0.5.0
monitoring | 2.9.5
pdfexport | 0.10.0
reactbundle | 0.7.0
reporting | 0.10.0

</body>
</html>

* Web browser and version: N/A
* Icinga 2 version used (`icinga2 --version`): 2.13.2-1
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: CentOS 7

## Additional context
Full debug output

```
[root@icinga12 ~]# icingacli reporting schedule --debug
Scheduling job Schedule 1 to run at 2022-01-07 09:53:00.
ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:210 with message: file_get_contents(): Filename cannot be empty
Starting browser process: HOME=/tmp/61d80d7c4fbc5/HOME exec '/usr/bin/google-chrome' '--bwsi' '--headless' '--disable-gpu' '--no-sandbox' '--no-first-run' '--disable-dev-shm-usage' '--remote-debugging-port=0' '--homedir=''/tmp/61d80d7c4fbc5/HOME' '--user-data-dir=''/tmp/61d80d7c4fbc5/HOME'
Caught browser output:
DevTools listening on ws://127.0.0.1:40534/devtools/browser/3e03f371-6eca-4491-815a-40f224df29ed

Transmitting CDP call: Target.createTarget(url)
Received CDP result: targetId
Transmitting CDP call: Log.enable()
Received CDP result: none
Transmitting CDP call: Network.enable()
Received CDP result: none
Transmitting CDP call: Page.enable()
Received CDP result: none
Transmitting CDP call: Console.enable()
Received CDP result: none
ERROR: ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:210 with message: file_get_contents(): Filename cannot be empty
PHP Fatal error:  Uncaught ErrorException: rmdir(/tmp/61d80d7c4fbc5/HOME/Default/Local Storage/leveldb): Directory not empty in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php:45
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'rmdir(/tmp/61d8...', '/usr/share/php/...', 45, Array)
#1 /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php(45): rmdir('/tmp/61d80d7c4f...')
#2 [internal function]: Icinga\File\Storage\TemporaryLocalFileStorage->__destruct()
#3 {main}
  thrown in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php on line 45

Fatal error: Uncaught ErrorException: rmdir(/tmp/61d80d7c4fbc5/HOME/Default/Local Storage/leveldb): Directory not empty in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php:45
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'rmdir(/tmp/61d8...', '/usr/share/php/...', 45, Array)
#1 /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php(45): rmdir('/tmp/61d80d7c4f...')
#2 [internal function]: Icinga\File\Storage\TemporaryLocalFileStorage->__destruct()
#3 {main}
  thrown in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php on line 45
```

**Comment by nilmerg** [comment]
Hey, that's a bug in Icinga Web 2 v2.9.x. You'll need to apply the change from https://github.com/Icinga/icingaweb2/pull/4636 to fix this error. Though, ultimately you'll also need https://github.com/Icinga/icingaweb2-module-pdfexport/pull/53 for the schedule to finally work.
