### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ipl\Sql\Config' not found in /usr/share/icingaweb2/modules/reporting/library/Reporting/Database.php:14

### ISSUE THREAD

**Issue by benhartwich** [Icinga/icingaweb2-module-reporting#12]
## To Reproduce

1.  clone first release
2. setup the database to mariadb
3. enable the module
4.  run icingacli reporting schedule run

## Expected behavior

The scheduler should run

## Your Environment

* Module version: 0.9.0
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About): 2.6.2
* Web browser and version: Chrome Windows 10
* Icinga 2 version used (`icinga2 --version`): r2.10.4-1
* PHP version used (`php --version`): PHP 7.1.25
* Server operating system and version: CentOS 7

## Additional context

PHP Fatal error:  Uncaught Error: Class 'ipl\Sql\Config' not found in /usr/share/icingaweb2/modules/reporting/library/Reporting/Database.php:14
Stack trace:
#0 /usr/share/icingaweb2/modules/reporting/application/clicommands/ScheduleCommand.php(20): Icinga\Module\Reporting\Cli\Command->getDb()
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Reporting\Clicommands\ScheduleCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/share/icingaweb2/modules/reporting/library/Reporting/Database.php on line 14

**Comment by benhartwich** [comment]
Found it by myself. please update the official icinga.com documentation regarding the dependency modules.

**Comment by dnsmichi** [comment]
That's been merged with #5 and the daily cron already refreshed it :)
