### ISSUE TITLE
Edit or send existing report not working, error Undefined property: stdClass::$template_id

### ISSUE THREAD

**Issue by gianmarco-mameli** [Icinga/icingaweb2-module-reporting#121]
## Describe the bug

Hi, after update to version 0.10.0 existing reports cannot be edited or sent, icingaweb2 and linux icinga-reporting service shows error

**Undefined property: stdClass::$template_id**

## To Reproduce

1. edit existing report or try start icinga-reporting service 

## Expected behavior

All works as expected, editing and sending

## Your Environment

businessprocess 		2.4.0 
cube 		1.2.0 
director 		master 
doc 		2.10.0 
fileshipper 		1.1.0 
grafana 		1.3.6 
idoreports 		0.10.0 
incubator 		0.14.0 
ipl 		v0.5.0 
map 		1.1.0 
monitoring 		2.10.0 
pdfexport 		0.10.1 
reactbundle 		0.9.0 
reporting 		0.10.0 
toplevelview 		0.3.3 
vspheredb 		1.2.1 
x509 		1.1.0 

Icinga2 version 2.13.2

**Comment by nilmerg** [comment]
Hi,

v0.10.0 requires a database upgrade: https://github.com/Icinga/icingaweb2-module-reporting/blob/master/schema/mysql-migrations/v0.10.0.sql

Though, this isn't documented yet. Thanks for reporting!

**Comment by gianmarco-mameli** [comment]
Hi @nilmerg 
thank you, problem solved, but i had to launch only the 2 alter tables statements in sql file, the table "template" was already present and correct.

Have a nice day
