### ISSUE TITLE
Exception Modulconfig

### ISSUE THREAD

**Issue by Bastilla123** [Icinga/icingaweb2-module-reporting#138]
## Describe the bug

I get in modulconfig a exception:

```
#0 /usr/share/php/Icinga/Application/Modules/Module.php(682): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Application/Modules/Module.php(645): Icinga\Application\Modules\Module->metadata()
#2 zend.view:///usr/share/icingaweb2/application/views/scripts/config/module.phtml(9): Icinga\Application\Modules\Module->getDependencies()
#3 /usr/share/php/Icinga/Web/View.php(259): include(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

## To Reproduce

1. Go in Icingaweb2 in Config ->Module -> Reporting then i get this execption on right side

## Expected behavior

Modul is activate and i don't get a exception

## Your Environment

* Module version: 0.10
* Postgres 11
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About):
* Web browser and version: Iron 100.0.5100.0
* Icinga 2 version used (`icinga2 --version`): r2.10.3-1
* PHP version used (`php --version`): 7.3.31-1
* Server operating system and version: Debian 10

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Could please provide the actual error message and the details from `Web -> System -> About`?

All the best,
Eric

**Comment by Bastilla123** [comment]
Hello Eric,

i get in About:

Undefined offset: 1

#0 /usr/share/php/Icinga/Application/Modules/Module.php(682): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Application/Modules/Module.php(615): Icinga\Application\Modules\Module->metadata()
#2 zend.view:///usr/share/icingaweb2/application/views/scripts/about/index.phtml(127): Icinga\Application\Modules\Module->getVersion()
#3 /usr/share/php/Icinga/Web/View.php(259): include(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}

Regards

**Comment by lippserd** [comment]
How did you install Web 2 and which version are you using? I would try the latest versions first. Your Icinga 2 is also quite outdated.

**Comment by Bastilla123** [comment]
I have a Raspberry Pi with Raspbian 10. I insert in sources.list:

deb https://packages.icinga.com/raspbian icinga-buster main
deb-src https://packages.icinga.com/raspbian icinga-buster main

I make update without a exception and after this i try apt upgrade icinga2-common and get:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 icinga2 : Hängt ab von: icinga2-common (= 2.10.3-2+deb10u1) aber 2.13.4-1.buster soll installiert werden
           Empfiehlt: icinga2-doc (= 2.10.3-2+deb10u1) aber 2.13.4-1.buster soll installiert werden
 icinga2-bin : Hängt ab von: icinga2-common (= 2.10.3-2+deb10u1) aber 2.13.4-1.buster soll installiert werden
 icinga2-ido-pgsql : Hängt ab von: icinga2-common (= 2.10.3-2+deb10u1) aber 2.13.4-1.buster soll installiert werden
E: Beschädigte Pakete

**Comment by Bastilla123** [comment]
I couldn't upgrade to newest version or i don't know how....

**Comment by darkpixel** [comment]
I just checked out master and am hitting the same issue.

```

Icinga Web 2 Version
2.8.2
Git commit
8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
7.4.30
Git commit date
2020-08-17
Copyright
© 2013-2022 The Icinga Project
 
   
Loaded modules
Name	Version
businessprocess	2.2.0
idoreports	0.9.0
ipl	v0.5.0
monitoring	2.8.2
reporting	0.9.2
```

**Comment by nilmerg** [comment]
@darkpixel You should upgrade at least to Icinga Web v2.9 to solve this.

**Comment by darkpixel** [comment]
FreeBSD packages are at 2.8 at the moment, and I don't feel like compiling from ports at the moment. I'll just wait a bit. :)

**Comment by nilmerg** [comment]
Icinga Web is at 2.11 now, I wouldn't expect that *the bit* is a short period :rofl:

**Comment by darkpixel** [comment]
You know how it is.  Get busy with a project, look up from your desk, and 3 years have passed. ;)
