### ISSUE TITLE
Emails are sent from root

### ISSUE THREAD

**Issue by ocstaron** [Icinga/icingaweb2-module-reporting#15]
When using the "Send" Button, the E-Mails are sent from "root@localhost.localdomain".

How can I configure the sender address?

I tried to find out from icingaweb2-module-reporting/library/Reporting/Mail.php, but I couldn't.
(Btw. I recognized a typo in line 43 there: it should be SERVER instead of SEVER, I think.)

Please tell me how to configure the address.

Kind regards and thanks,
Oliver

**Comment by lippserd** [comment]
Hi,

Tanks for the report. Do you want to create a PR for the typo?

You may add the following to the Icinga Web 2 web server configuration:

`SetEnv SERVER_ADMIN reporting@acme`

But I think it make sense to have this configureable in the GUI.

Best,
Eric

**Comment by ocstaron** [comment]
Hi Eric,

thanks for your reply.

When I set Environment=SERVER_ADMIN=reporting@acme
in /etc/systemd/system/icinga-reporting.service and send a report via
scheduler it works.

It doesn't work setting it in the apache2 config file and send it from the GUI.
It seems icingaweb2-module-reporting/library/Reporting/Web/Forms/SendForm.php is used then,
where this is not implemented.

Am I wrong?

Kind regards,
Oliver

**Comment by dnsmichi** [comment]
Maybe it is worthwhile to modify the MTA, a howto similar to this question is available in the community channels: https://community.icinga.com/t/change-mail-from-for-icinga-notifications/190
