### ISSUE TITLE
file_get_contents(): Filename cannot be empty

### ISSUE THREAD

**Issue by mmarodin** [Icinga/icingaweb2-module-reporting#17]
Hi, I'm testing the new reporting module.

When it runs a scheduled System report the _icinga cli_ exit with the error:
_[root@mlv-mon02 modules]# icingacli reporting schedule run
Scheduling job Schedule 5 to run at 2019-05-02 16:10:00.
ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:149 with message: file_get_contents(): Filename cannot be empty
ERROR: ErrorException in /usr/share/icingaweb2/modules/reporting/library/Reporting/Reports/SystemReport.php:27 with message: Trying to get property of non-object
[root@mlv-mon02 modules]#_

When it runs a scheduled Host-SLA report I have a similar warning:
_[root@mlv-mon02 modules]# icingacli reporting schedule run
Scheduling job Schedule 5 to run at 2019-05-02 16:48:00.
ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:149 with message: file_get_contents(): Filename cannot be empty
Scheduling job Schedule 4 to run at 2019-06-02 15:50:02._
But the _icinga cli_ doen't exit and the report run and arrived me via email.

Scheduling a Service-SLA report all is ok.

Both of these PDF reports arrive via email, but without graphs, only with percentuals written in text. But I can see the green/red box via icinga2web console.
Is it normal?

![icinga2_reporting-01](https://user-images.githubusercontent.com/2854369/57082142-71e37f00-6cf6-11e9-9b7b-da080aa0e860.png)

![icinga2_reporting-02](https://user-images.githubusercontent.com/2854369/57082223-98091f00-6cf6-11e9-8148-d69fa412ef09.png)

Please let me know, about the _file_get_contents()_ error and about the PDF missing graphs.
Thanks

My Environment:
* Module version: 0.9.0
* Dependent module versions: reactbundel (v0.5.1), ipl (v0.2.1), pdfexport (0.9.0)
* Icinga Web 2 version and modules (System - About): 2.6.3, director grafana idoreports incubator ipl monitoring pdfexport reactbundle reporting vspheredb x509
* Web browser and version: Firefox ESR 60.6.1
* Icinga 2 version used (`icinga2 --version`): r2.10.4-1
* PHP version used (`php --version`): 7.1.8
* Server operating system and version: Oracle Linux Server release 7.6

**Comment by mmarodin** [comment]
I've just read this post, https://community.icinga.com/t/icinga-reporting/1096.
I think I can close this issue

**Comment by piotr3439** [comment]
I still do not understand whether the report sent by e-mail is supposed to look different than the one in the browser?

**Comment by willfurnell** [comment]
I have exactly the same issue - I don't see how that post resolved your issue?
