### ISSUE TITLE
Uncaught Error: Call to undefined method 

### ISSUE THREAD

**Issue by dinbhar** [Icinga/icingaweb2-module-reporting#177]
Getting this error while creating reports.

Uncaught Error: Call to undefined method Icinga\Module\Reporting\Web\Forms\ReportForm::translate() in /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Forms/ReportForm.php:38
Stack trace:
#0 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Reporting\Web\Forms\ReportForm->assemble()
#1 /usr/share/icinga-php/ipl/vendor/ipl/html/src/Form.php(197): ipl\Html\HtmlDocument->ensureAssembled()
#2 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php(99): ipl\Html\Form->handleRequest()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->newAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#6 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#7 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#9 {main}
thrown

Icinga Web 2 Version | 2.11.1
PHP Version | 8.1.13

Loaded Libraries

icinga/icinga-php-thirdparty | 0.11.0
icinga/icinga-php-library | 0.9.1

**Comment by yhabteab** [comment]
Hii @dinbhar, thanks for the report.

Since these changes have not yet been released, you must either check out a release tag, e.g. `0.10.0` or check out `ipl-html` the master as well, which is not recommended.
