### ISSUE TITLE
Template can not be edited

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingaweb2-module-reporting#186]
## Describe the bug

Icinga is running with ICINGA DB. Now I wanted to customize the template for reporting and I get the following error message:
```
Uncaught Error: Call to undefined method ipl\Html\FormElement\TextElement::hasBeenValidatedAndIsNotValid() in /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/DivDecorator.php:67
Stack trace:
#0 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(294): Icinga\Module\Reporting\Web\DivDecorator->assemble()
#1 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(514): ipl\Html\HtmlDocument->ensureAssembled()
#2 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(430): ipl\Html\HtmlDocument->render()
#3 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(408): ipl\Html\HtmlDocument->renderWrappedDocument()
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(518): ipl\Html\HtmlDocument->renderWrapped()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#7 /usr/share/icinga-php/ip

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

## To Reproduce

1. Try to edit an existing template
. 

## Expected behavior

Template editor will open

## Your Environment

Module version: 0.10.0
Dependent module versions: 
Module ipl: v0.5.0
Icinga DB Web version (System - About): 1.0.2
Icinga Web 2 version (System - About):2.11.4
Web browser: Chrome 110.0.5481.100
Icinga 2 version (icinga2 --version): r2.13.7-1
Icinga DB version (icingadb --version): v1.1.0
PHP version used (php --version): 7.4
Server operating system and version: Debian 10

**Comment by nilmerg** [comment]
> Module version: 0.10.0

Please make sure this is correct. The class the error mentions does not exist anymore in this version, so it should not occur.

**Comment by TheCry** [comment]
Ohhh. Very embarrassing. I had not done the checkout. Sorry!
