### ISSUE TITLE
See if a report has a schedule from the reports page

### ISSUE THREAD

**Issue by LucaMH** [Icinga/icingaweb2-module-reporting#193]
## Is your feature request related to a problem? Please describe.
Currently we have to misuse the name of a report to make everybody aware that a report is running on a shedule.
This makes the name of the send out file in the report ugly.

Webview:
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/22506082/d7b3fe3f-8f82-471c-9a37-8fe61069e3af)

filename in mail:
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/22506082/b2eeec46-90f2-4f19-b317-fe6bad474839)

## Describe the solution you'd like
Soulutions which came to my mind:
a) decouple file name form reportrame (simmilar as in hosts in monitoring, have a display name and a report name)
b) create a colum in the webview where you can see if a report runs on a schedule (sounds like a better and more complete solution to me)
example:
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/22506082/b9199a27-c3cb-4cc7-a9f9-9a8c1522a0cc)

Thanks!
Luca

**Comment by yhabteab** [comment]
Duplicated of #179
