### ISSUE TITLE
error trying to create schedule

### ISSUE THREAD

**Issue by fromanm1** [Icinga/icingaweb2-module-reporting#195]
Reports works perfectly, it manualy sends emails with pdf  without any problem. but when I try to create an schedule I got an error "SQLSTATE[HY000]: General error: 1364 Field 'start' doesn't have a default value" (no matter what date or type  or frequency, it's always the same error)

## To Reproduce

1.  install reports module
2.  follow the instruccions to configure mysql db 
3.  enable reports
4.  create a report
5.  create a schedule

## Your Environment

* Module version:  0.10.0
* Dependent module versions:  pdfexport 0.10.2
* Icinga Web 2 version: 2.11.4
* icingadb web: 1.0.2-1
* icingadb: 1.1.0-1

* icinga Web 2 modules:
Loaded Modules
company		1.0.0	Configure
grafana		2.0.3	Configure
icingadb		1.0.2	Configure
idoreports		0.9.1	Configure
pdfexport		0.10.2	Configure
reporting		0.10.0	Configure

* Web browser and version: chrome 115.0.5790.110 (Build oficial) (64 bits) 
* Icinga 2 version used (`icinga2 --version`): r2.14.0-1
* PHP version used (`php --version`):  8.1.21
* Server operating system and version: CentOS 7.9.2009
* database: MariaDB 10.5.16-1.el7

thanks!

**Comment by thrashiii** [comment]
same problem here with debian 10.13

**Comment by yhabteab** [comment]
Hi, please do not use the master branch, but a release tag `0.10.0` instead.

**Comment by thrashiii** [comment]
thank you, that was the problem for me. Since I use the release tag the scheduler works.
