### ISSUE TITLE
Send mail is broken with zf1-future

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2-module-reporting#200]
## Describe the bug

Passing additional params to Zend mail triggers `Potential code injection in From header` error, when trying to send reports.
https://github.com/Icinga/icingaweb2-module-reporting/blob/b1dd215feff8c0976495b72e8e6cd492d1283712/library/Reporting/Mail.php#L104-L105

Upstream issue https://github.com/Shardj/zf1-future/issues/326

**Comment by nilmerg** [comment]
created https://github.com/Icinga/icinga-php-thirdparty/issues/17 for this
