### ISSUE TITLE
Uncaught Error: Call to undefined method

### ISSUE THREAD

**Issue by tbals** [Icinga/icingaweb2-module-reporting#205]
## Describe the bug

I have installed like described here. After enabling all I can see the new Menu "Reporting". When I click to Reporting->Reports I get only this message:

`Uncaught Error: Call to undefined method ipl\Web\Widget\ButtonLink::openInModal() in /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php:35
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->indexAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#3 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#4 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#6 {main}
thrown

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}`

## Your Environment
Icinga Web 2 Version: 2.11.4
PHP-Version: 8.1.2-1ubuntu2.14
OS: Ubuntu 22.04.3
Database: PostgreSQL 14.9

Loaded Libraries:

icingadb |   | 1.0.2
idoreports | 0.10.1
monitoring  | 2.11.4
pdfexport  | 0.10.2
reporting  | 0.10.0

**Comment by yhabteab** [comment]
Hi @tbals, please do not use the master branch, but a release tag `0.10.0` instead.

**Comment by tbals** [comment]
> Hi @tbals, please do not use the master branch, but a release tag `0.10.0` instead.

Thank you, now its working:
`# git clone --branch v0.10.0 https://github.com/Icinga/icingaweb2-module-reporting.git reporting`

But the documentation (https://icinga.com/docs/icinga-reporting/latest/doc/02-Installation/, https://icinga.com/blog/2019/06/17/icinga-reporting-hands-on/) dont say something about a release tag.

**Comment by yhabteab** [comment]
It is always discouraged to use the `master` branch in production as it is the development branch for the upcoming release, i.e. it sometimes requires different dependencies than the stable releases and is always subject to change that might introduce breaking changes.
