### ISSUE TITLE
Reporting page not showing after refresh.

### ISSUE THREAD

**Issue by Alemmi** [Icinga/icingaweb2-module-reporting#217]
## Description of the bug

Reporting page not showing after refresh.

## To Reproduce

1. Create a report
2. Select a report
3. Close the left panel
4. Refresh the page by browser button (not by the dedicated button in Icinga)

## Expected behavior

After refreshing the reporting page, it has to show.

## Screenshots

1. Create a report
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/24527637/399e8ba8-2cd6-4568-84c0-5ecddedcacd4)

3. Select the report
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/24527637/1262c645-08de-4146-9c55-7e7b936c9c27)

4. Close the left panel
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/24527637/6fa72529-a047-4193-8a13-05459ab0b73f)

5. After F5(Refresh)
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/24527637/40192613-2427-47d8-af85-11a39b4bb69e)

P.S. If I refresh with the IcingaWeb2 refresh button, everything works
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/24527637/b6e29d54-73a4-4137-9ddd-0e9e236236b3)

## Your Environment

* Module version: 1.0.0
* Dependent module versions: icinga-php-thirdparty==0.12.0,icinga-php-library==0.13.0,pdfexport=0.10.2
* Icinga Web 2 version and modules (System - About): icingaweb2==2.11.4
* Web browser and version: Chrome 117.0.5938.92
* Icinga 2 version used (`icinga2 --version`): 2.14.0
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Official Docker Image (host O.S.: Fedora 38)

## Your Environment

* Module version: 1.0.0
* Dependent module versions: Icinga-php-thirdparty==0.12.0,Icinga-php-library==0.13.0,pdfexport=0.10.2
* Icinga Web 2 version and modules (System - About): icingaweb2==2.11.4
* Web browser and version: Chrome 117.0.5938.92
* Icinga 2 version used (`icinga2 --version`): 2.14.0
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Official Docker Image (host O.S.: Fedora 38)

**Comment by yhabteab** [comment]
Hi @Alemmi, thanks for reporting.
