### ISSUE TITLE
icinga-reporting.service causes several db-connections

### ISSUE THREAD

**Issue by tectumopticum** [Icinga/icingaweb2-module-reporting#219]
## Describe the bug
icinga-reporting.service-daemon is running on the master-server:
 systemctl status icinga-reporting.service
● icinga-reporting.service - Icinga Reporting Scheduler
     Loaded: loaded (/etc/systemd/system/icinga-reporting.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2023-11-10 11:45:04 CET; 53min ago
   Main PID: 11643 (icingacli)
      Tasks: 1
     CGroup: /system.slice/icinga-reporting.service
             └─ 11643 /usr/bin/php /usr/bin/icingacli reporting schedule run

After a short time more and more connections to the mariadb were opened:
`select id,user,db,command,time,state,info,progress from information_schema.processlist where user = 'reporting';
+-------+-----------+-----------+---------+------+-------+------+----------+
| id    | user      | db        | command | time | state | info | progress |
+-------+-----------+-----------+---------+------+-------+------+----------+

| 81951 | reporting | reporting | Sleep   |  286 |       | NULL |    0.000 |
| 81369 | reporting | reporting | Sleep   |  586 |       | NULL |    0.000 |
| 81078 | reporting | reporting | Sleep   |  886 |       | NULL |    0.000 |
| 80356 | reporting | reporting | Sleep   | 1186 |       | NULL |    0.000 |
| 79647 | reporting | reporting | Sleep   | 1486 |       | NULL |    0.000 |
| 78906 | reporting | reporting | Sleep   | 1786 |       | NULL |    0.000 |
| 77753 | reporting | reporting | Sleep   | 2086 |       | NULL |    0.000 |
| 76648 | reporting | reporting | Sleep   | 2386 |       | NULL |    0.000 |
| 76311 | reporting | reporting | Sleep   | 2686 |       | NULL |    0.000 |
| 76019 | reporting | reporting | Sleep   | 2986 |       | NULL |    0.000 |
| 75784 | reporting | reporting | Sleep   | 3286 |       | NULL |    0.000 |
| 75550 | reporting | reporting | Sleep   | 3586 |       | NULL |    0.000 |
| 75300 | reporting | reporting | Sleep   | 3886 |       | NULL |    0.000 |
| 75019 | reporting | reporting | Sleep   | 4186 |       | NULL |    0.000 |
+-------+-----------+-----------+---------+------+-------+------+----------+
14 rows in set (0.001 sec)`

a few minutes later:

` select count(*) from information_schema.processlist where user = 'reporting';
+----------+
| count(*) |
+----------+
|       17 |
+----------+`

The number of connections increased up to 150 (mariadb-default limit: 151), 

## To Reproduce

1. start with a working reporting-module 0.9.2
2. update to 1.0.0: 
/usr/share/icingaweb2/modules/reporting # git pull
git checkout v1.0.0
update db-schema
3. observe 'mariadb -e "SHOW PROCESSLIST;"' or query 'information_schema.processlist'
4. stop daemon: systemctl status icinga-reporting.service
5. observe 'mariadb -e "SHOW PROCESSLIST;"' or query 'information_schema.processlist'

## Expected behavior
only a few connections should be held open by all modules (in our environment usually < 25)

## Screenshots

![grafik](https://github.com/Icinga/icingaweb2-module-reporting/assets/66269591/50811178-e273-43db-b39c-d79b42ae9963)

## Your Environment

* Module version: 1.0.0
* Dependent module versions: icinga/icinga-php-thirdparty: 0.12.0 / icinga/icinga-php-library: 0.13.0
* Icinga Web 2 version and modules (System - About):
icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
businessprocess 2.4.1     enabled   A Business Process viewer and modeler
clustergraph   1.0.5     enabled   Visual representation of Icinga Clusters
company        1.0.0     enabled   Company Theme example
cube           1.3.2     enabled   Cube for Icinga Web
director       1.11.0    enabled   Director - Config tool for Icinga 2
doc            2.12.0    enabled   Documentation module
eventtracker   0.9.0     enabled   Operator Dashboard to track Incidents from various sources
fileshipper    1.2.0     enabled   Fileshipper for Icinga Director
grafana        2.0.3     enabled   Grafana - A perfdata visualisation module
icingadb       1.1.0     enabled   Icinga DB Web
idoreports     0.10.0    enabled   Reports for IDO
iet            0.9.0     enabled   iET module for Icinga Web 2
incubator      0.20.0    enabled   Incubator provides bleeding-edge libraries
map            1.1.0     enabled   Map - Visualize your hosts and service status
migrate        2.12.0    enabled   Migrate module
pdfexport      0.10.1    enabled   PDF Export via Google Chrome/Chromium
prime          1.0.0     enabled   ImportSource for Cisco Prime Infrastructure
reporting      1.0.0     enabled   Reporting
vspheredb      1.7.1     enabled   Icinga vSphere® Integration
x509           1.3.1     enabled   Scan and view X.509 certificate usage
* Web browser and version:  Firefox 115.4.0esr (64-Bit)
* Icinga 2 version used (`icinga2 --version`): 2.14.0
* PHP version used (`php --version`): 8.0.30
* Server operating system and version: SLES 15 SP4

## Additional context

might be an issue related to os-patches or updated libraries/packages because in our prod-env it didn't appear directly after updating the module. It occured after we've patches the os and rebooted the master-server.

**Comment by yhabteab** [comment]
Hi @tectumopticum, thanks for reporting!

Just for the record, this is caused by the way the default PHP [garbage collector](https://www.php.net/manual/en/features.gc.collecting-cycles.php) works.

> When the garbage collector is turned on, the cycle-finding algorithm as described above is executed whenever the root buffer runs full. The root buffer has a fixed size of 10,000 possible roots

This means, for instance, if you reduce the daemon configuration reload interval from `5m` to `5s` or `2s`, you will notice that it will always call `ScheduleCommand#fetchSchedules()` and create a `Query` instance with a new database connection each time. However, the `Query` instance is not being destructed after the function returns, but PHP simply waits until the above mentioned buffer becomes full and then destroys all created and dangling query instances, each of which has its own database connection. To fix this, we can either force PHP's garbage collection on every call to `fetchSchedules()` using [`gc_collect_cycles()`](https://www.php.net/manual/en/function.gc-collect-cycles.php) or we can make the `Database` trait a singleton and only open one connection per request.
