### ISSUE TITLE
Can't view reports

### ISSUE THREAD

**Issue by maxifrdz** [Icinga/icingaweb2-module-reporting#22]
I can't seem to view any reports, whenever I create a report all I can see is phpinfo.

![image](https://user-images.githubusercontent.com/24704090/58908631-76c99300-86e7-11e9-8e0f-0006e3e0fc68.png)
![image](https://user-images.githubusercontent.com/24704090/58908664-83e68200-86e7-11e9-9e6f-81ceb6acd9dd.png)

I also can't select another kind of report other than System.

![image](https://user-images.githubusercontent.com/24704090/58908459-01f65900-86e7-11e9-84dc-372ad62cdf08.png)

This is happening on two systems, one is Debian 8 with PHP 5.6 and the other is Debian 9 with PHP 7.

**Environment**

MODULE | VERSION
-----------|-----------
company|0.0.0
director|1.6.2
doc|2.6.3
grafana|1.3.5
incubator|v0.3.0
ipl|v0.3.0
monitoring|2.6.3
pdfexport|0.9.0
reactbundle|v0.6.0
reporting|0.9.0
vspheredb|1.0.3

**Web browser and version:** Chrome 75
**PHP version used (php --version):** PHP 5.6.40-0+deb8u4 (cli) (built: Jun  3 2019 09:30:09) / PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
**Server operating system and version:** Debian 8 / Debian 9

Am I missing something?
Thanks

**Comment by dnsmichi** [comment]
You're missing the idoreports module which provides the data source for Host/Service reports.
