### ISSUE TITLE
Disable CSP for cli commands

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2-module-reporting#227]
## Describe the bug

Don't require a strict CSP for any cli interactions. Trying to send reports with templates produces a messy stacktrace due to the class `CoverPage` registering `StyleWithNonce` without considering the cli commands.

ref/NC/51802

**Comment by tbauriedel** [comment]
ref/NC/805384

**Comment by tbauriedel** [comment]
ref/NC/807726

**Comment by yhabteab** [comment]
Fixed with https://github.com/Icinga/ipl-web/pull/216
