### ISSUE TITLE
Scheduler does not work with PDF type

### ISSUE THREAD

**Issue by gianlucapiccolo** [Icinga/icingaweb2-module-reporting#229]
## Describe the bug

When a report is scheduled to be sent via mail as a PDF, after the first iteration the scheduler stops to work.
The scheduled job to send the report PDF via mail breaks the scheduler, no jobs are executed anymore after that.

## To Reproduce

1. Import the attached reporting database ([reporting-broken-scheduler.zip](https://github.com/Icinga/icingaweb2-module-reporting/files/14511002/reporting-broken-scheduler.zip))
2. Configure the pdfexport module to use the local Chrome binary (`/usr/bin/google-chrome`)
3. Run `icingacli reporting schedule run --debug`
4. Wait at least 3 minutes.
5. Pay attention: the scheduler stops to execute next scheduled jobs after the first time.

## Expected behavior

The scheduler should not stop after the first execution but it should continue to send the report as scheduled.

## Your Environment

* Icinga Web 2 version and modules (System - About): 
![image](https://github.com/Icinga/icingaweb2-module-reporting/assets/2795394/97ac648b-4df1-40db-8853-f7b9fdc0e88d)
* Server operating system and version: Debian 11.9
* /usr/bin/google-chrome --version: Google Chrome 122.0.6261.111

## Additional context

From a little bit of investigation, it could be related to a conflict between the `React\EventLoop\LoopInterface` object instanciated into the reporting scheduler and the one instanciated in the `icingaweb2-module-pdfreport:library/Pdfexport/HeadlessChrome.php`.

**Comment by yhabteab** [comment]
ref/IP/52505
