### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-reporting#245]
## Describe the bug

Host and service actions provided by the module are not working

## To Reproduce

1. Have the module enabled
2. Try the action at a host or service

## Expected behavior

I get a report quickly.

## Your Environment

* Module version: 0.10.0
* Dependent module versions: 0.10.0
* Icinga Web 2 version and modules (System - About): 2.12.1
* Web browser and version: Firefox

## Additional context

It seems like the reload after choosing the Timeframe does reload the whole page and breaks the wizard.

**Comment by nilmerg** [comment]
Please explain what's not working. What happens exactly?

Also: I cannot reproduce with either Firefox nor Chrome. At least, as long as I don't know what to look out for specifically, all seems to work.

**Comment by dgoetz** [comment]
Fix by updating to the latest version.
