### ISSUE TITLE
Problem with job schedule

### ISSUE THREAD

**Issue by cristorrian** [Icinga/icingaweb2-module-reporting#27]
## Describe the bug
I have a problem when execute the schedule utility on module reporting.

I have this output.

> Uncaught Error: Class 'Icinga\Module\Reporting\DivDecorator' not found in /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Forms/ScheduleForm.php:56
Stack trace:
#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(258): Icinga\Module\Reporting\Web\Forms\ScheduleForm->assemble()
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/Form.php(61): ipl\Html\HtmlDocument->ensureAssembled()
#2 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(96): ipl\Html\Form->handleRequest(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->scheduleAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('scheduleAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/sh

> #0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

## To Reproduce

1. Install all dependences for the module reporting.
2. Install module reporting.
3. Install module Ido-reports.
4. Configure service icinga-reporting.service to systemd, enable and start it.

## Your Environment

- Module version: 0.9.1
- Dependent module versions:
  - pdfexport: 0.9.1
  - reactbundle: 0.6.0
  - ipl: 0.3.0
- Icinga Web 2 version and modules:
  - Icinga Web 2 version: 2.6.3
  - Director module version: 1.6.2
  - Graphite version: 1.1.0
  - IdoReports module version: 0.9.1
  - Monitoring module version: 2.6.3
- Web browser and version: Mozilla Firefox Quantum - v63.0.3
- Icinga 2 version used: r2.10.5-1
- PHP version used: 7.2.19
- Server operating system and version: CentOS Linux release 7.6.1810 (Core)

**Comment by dnsmichi** [comment]
Moved, please pick the correct project next time.

**Comment by cristorrian** [comment]
> Moved, please pick the correct project next time.

Ok sorry, i'm newbie on GitHub.

**Comment by dnsmichi** [comment]
Also, please provide more insights on your environment by filling in the list below:

## Your Environment

* Module version: 
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About):
* Web browser and version:
* Icinga 2 version used (`icinga2 --version`):
* PHP version used (`php --version`):
* Server operating system and version:

**Comment by dnsmichi** [comment]
Ok, I think, I can see it - can you test the patch in the linked PR? It only requires a minor file edit, so you can do it on your own with your preferred editor.

**Comment by cristorrian** [comment]
> Ok, I think, I can see it - can you test the patch in the linked PR? It only requires a minor file edit, so you can do it on your own with your preferred editor.

Yes it work, but this time I have another error with other class.



Uncaught Error: Class 'Icinga\Module\Reporting\Web\Forms\Flatpickr' not found in /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Forms/ScheduleForm.php:66
Stack trace:
#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(258): Icinga\Module\Reporting\Web\Forms\ScheduleForm->assemble()
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/Form.php(61): ipl\Html\HtmlDocument->ensureAssembled()
#2 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(96): ipl\Html\Form->handleRequest(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->scheduleAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('scheduleAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

**Comment by cristorrian** [comment]
> Ok, I think, I can see it - can you test the patch in the linked PR? It only requires a minor file edit, so you can do it on your own with your preferred editor.

Yes it works thanks!!!

**Comment by dnsmichi** [comment]
Leaving this open for the next release planning @lippserd

**Comment by cristorrian** [comment]
> Leaving this open for the next release planning

Ok
