### ISSUE TITLE
calendar not opening

### ISSUE THREAD

**Issue by CorHortensius** [Icinga/icingaweb2-module-reporting#32]
## Describe the bug

When you want to schedule a Start in de Reporting module for mailing a report, the calendar button is not working.

## To Reproduce

1. Open een report
2. go to schedule
3. click on calendar icon

## Expected behavior

You expect that there will pop-up a calendar and time picker, so you can choose from when the schedule should run.

## Screenshots

![image](https://user-images.githubusercontent.com/20768087/63430576-2ed02780-c41d-11e9-8923-ec7e91b3e97a.png)

## Your Environment

* Module version: 0.9.2
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About): 2.7.1
* Web browser and version: chrome + edge
* Icinga 2 version used (`icinga2 --version`): 2.10.5-1
* PHP version used (`php --version`): 7.2
* Server operating system and version: ubuntu 18.04

## Additional context

when typing in manually the date + time in the right format `30-07-2019 00:00` it is working.

**Comment by dnsmichi** [comment]
Which Chrome and Edge versions are you using? Also, are there any errors logged in the browser's dev console when you click on the datetime picker?

**Comment by CorHortensius** [comment]
Edge: 44.18362.267.0
EdgeHTML: 18.18362

Chrome: 76.0.3809.132
The cross next to the datetime picker is also doing nothing.
The console is not showing any error's.
everything is behind an NginX server.

![image](https://user-images.githubusercontent.com/20768087/64114375-10f3b280-cd8d-11e9-834e-c987115ec7f1.png)

![image](https://user-images.githubusercontent.com/20768087/64114645-d3dbf000-cd8d-11e9-9979-587a24901c43.png)

```
<div class="reporting-flatpickr form-element">
<label>Start</label>
<input name="start" required="" type="text" placeholder="Choose date and time" value="2019-08-21 14:10" data-input="" data-enable-time="">
<button class="icon-calendar" type="button" data-toggle=""></button>
<button class="icon-cancel" type="button" data-clear=""></button>
</div>
```

I also figured out that the schedule did not send emails.
When i manual say send a email with pdf, it's working fine.

**Comment by lippserd** [comment]
Hi,

Should be fixed in the master branch and release version 0.9.2. If you still face this problem, please do not hesitate to create a new issue.

Best,
Eric
