### ISSUE TITLE
Reporting module is not working throwing a SQL error

### ISSUE THREAD

**Issue by shamzu91** [Icinga/icingaweb2-module-reporting#33]
## Describe the bug

After installing icingaweb2-module-reporting and all dependencies I am getting a SQL error 
saying "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icinga.report' doesn't exist"

## To Reproduce

1. Set up icinigaweb2
2. Install icingaweb2-module-reporting and IDO Reports(followed the link https://icinga.com/2019/06/17/icinga-reporting-hands-on/)
3. Click on Reports

## Expected behavior

Should be able to generate reports

## Screenshots
![image](https://user-images.githubusercontent.com/20651526/63956708-97b24200-caa4-11e9-8faf-9c3af5f144ca.png)

## Your Environment

* icingaweb2-module-reporting version 0.9.2
* Dependent module versions: 
  icingaweb2-module-reactbundle 0.6.0
  icingaweb2-module-ipl 0.3.0
  icingaweb2-module-pdfexport 0.9.1 

* Icinga Web 2 version and modules (System - About): 2.6.3-1
* Web browser and version: chrome+IE
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): PHP 5.4.16
* Server operating system and version: CentOS Linux release 7.6.1810 (Core)

## Additional context

As per my assumption I have checked the IDO_DB icinga2 but couldn't find a 'reporting' table.
Also checked if all the DB schema/upgrades are applied

**Comment by dnsmichi** [comment]
This module needs a dedicated database with schema imports. Also, that needs to be configured as resource made available to the module.

https://icinga.com/docs/reporting/latest/doc/02-Installation/#database-setup

**Comment by shamzu91** [comment]
Hi dnsmichi,

Thank you for the reply. It helped to find the error.

I had pointed resource wrong database under reporting module back-end. Corrected to 'reporting' database and now I can generate reports. 

Addition to this I have directly upgraded my Icinga2 box from 2.3.x version to 2.10.5(Apologies, forgot to mention in first comment). I thought some missing part in upgrade path caused the above error.

Thanks again.

**Comment by dnsmichi** [comment]
Glad you figured it out by yourself. You can reach a broader audience with asking such things which are not exactly a bug, on https://community.icinga.com ;)
