### ISSUE TITLE
BUG:  Schedule funtion throwing an error

### ISSUE THREAD

**Issue by fireheadman** [Icinga/icingaweb2-module-reporting#35]
## Describe the bug

Unsure what piece is missing, I followed the installation top to bottom.

## To Reproduce

1. Create a job
2. then select job
3. then select "schedule"  

## Expected behavior

Was expecting a schedule dialogue to start

## Screenshots

![image](https://user-images.githubusercontent.com/19847195/64896794-4f675800-d63e-11e9-9f46-1f1574e4144a.png)

## Your Environment

* Module version: v0.9.1
* Dependent module versions: 
pdfexport v0.9.1
ipl v0.3.0
reactbundle v0.6.0
* Icinga Web 2 version and modules (System - About): v2.6.3
* Web browser and version: firefox (macos)
* Icinga 2 version used (`icinga2 --version`):
* PHP version used (`php --version`):
* Server operating system and version: redhat 7.6

## Additional context

I originally started with v0.9.0, the upgraded to v0.9.1.
This was performed by deleting /usr/share/icingaweb2/modules/[reporting|idoreports|pdfexport]
and downloading the new modules.

**Comment by fireheadman** [comment]
This problem explains why the CLI command is hanging
` sudo icingacli reporting schedule run`

I apologize in advance, I filed a bug report for that under the IDOReports (got the 2 confused)
https://github.com/Icinga/icingaweb2-module-idoreports/issues/15

**Comment by fireheadman** [comment]
Was able to manually apply the upcoming commits to v0.9.2 to correct this issue.

the CLI command however still hangs.
And I also noticed when the schedule is created and saved, nothing ever happens.

Redacted my real email address.
![image](https://user-images.githubusercontent.com/19847195/64898412-4da09300-d644-11e9-9f7f-14ba5a11c735.png)

**Comment by fireheadman** [comment]
UPDATE:
I'm getting the hang of this as I go... 
Now I understand the workflow.
Create a schedule, then execute either the service or icingacli schedule run cmd.  (It working)

Did want to mention this output from the icingacli schedule run command...

> [user@icinga01 ~ 13228]$ sudo icingacli reporting schedule run
> Scheduling job Schedule 6 to run at 2019-09-13 16:37:00.
> Scheduling job Schedule 10 to run at 2019-09-13 17:00:00.
> **ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:149 with message: file_get_contents(): Filename cannot be empty**
> Scheduling job Schedule 6 to run at 2019-09-13 16:38:00.
> **ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:149 with message: file_get_contents(): Filename cannot be empty**
> Scheduling job Schedule 6 to run at 2019-09-13 16:39:01.
> **ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:149 with message: file_get_contents(): Filename cannot be empty**
> Scheduling job Schedule 6 to run at 2019-09-13 16:40:01.
> **ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:149 with message: file_get_contents(): Filename cannot be empty**
> Scheduling job Schedule 6 to run at 2019-09-13 16:41:01.

**Comment by lippserd** [comment]
Hi,

Should be fixed in the master branch and release version 0.9.2. If you still face this problem, please do not hesitate to create a new issue.

Best,
Eric
