### ISSUE TITLE
Scheduler fails with message: ini_set(): Headers already sent. You cannot change the session module’s ini settings at this time

### ISSUE THREAD

**Issue by BornTKill** [Icinga/icingaweb2-module-reporting#38]
Dear,

I have recently upgrade from ubuntu 16 to 18 so php has been upgraded from 7.0 to 7.2 and now when i do icingacli reporting scheduler run, I get ;

ERROR: ErrorException in /usr/share/php/Icinga/Web/Session/PhpSession.php:87 with message: ini_set(): Headers already sent. You cannot change the session module’s ini settings at this time

Workaround applied : Comment out : 

/* foreach ($options as $sessionVar => $value) {
            if (ini_set(“session.” . $sessionVar, $value) === false) {
                Logger::warning(
                    ‘Could not set php.ini setting %s = %s. This might affect your sessions behaviour.’,
                    $sessionVar,
                    $value
                );
            }
        }*/

Any ideas ?

**Comment by neubi4** [comment]
Hey,

we also have this problem running the scheduling job on php7.3. I tried to debug it, but i have no idea where the headers are sent before trying of settings the ini_set.

Icingaweb2 v2.7.3

```
$ php --version
PHP 7.3.13 (cli) (built: Dec 17 2019 10:29:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
```

Modules:

```
azure | 0.6.3
businessprocess | 2.2.0
cube | 1.0.1
director | 1.7.2
grafana | master
idoreports | 0.9.1
incubator | 0.5.0
ipl | v0.3.1
map | 1.1.0
monitoring | 2.7.3
pdfexport | 0.9.1
reactbundle | 0.7.0
reporting | 0.9.2
t-systems | 1.0
```

**Comment by lippserd** [comment]
Hi @neubi4 and @BornTKill,

Could you please either test this PR https://github.com/Icinga/icingaweb2/pull/4065 or upgrade Web to 2.8.0 RC1?

I think that this is related to a change in Icinga Web 2 where we automatically load all enabled modules in CLI actions which also triggers the scripts `configuration.php` and `run.php`. Some modules access the authentication object there which fails in CLI because we don't have a user object.

All the best,
Eric

**Comment by neubi4** [comment]
Hi @lippserd,

i upgraded the local environment to 2.8.0 RC1 and this fixed the problem. Thanks for your help! :)

**Comment by lippserd** [comment]
Hi,

Thanks for the feedback.

I'm not quite sure what's the best process here now. I think we'll leave it open until Web 2.8.0 is released.

All the best,
Eric

**Comment by henningw** [comment]
The web 2.8.0 has been released, so it can be probably closed.
