### ISSUE TITLE
Problem with Job Schedule on pdf file. (Host SLA and Service SLA)

### ISSUE THREAD

**Issue by cristorrian** [Icinga/icingaweb2-module-reporting#47]
## Describe the bug

When schedule Host SLA or Service SLA with pdf format i get a pdf file in plain text without red and green bubbles in my email, but when i send the pdf file trought manual sent i obtain the correct pdf with red and green bubbles.

## To Reproduce

Send pdf file to email trought job schedule.

## Expected behavior

The obtained pdf file has the red and green bubbles.

## Screenshots

**PDF Job Schedule**
![imagen](https://user-images.githubusercontent.com/51986864/71980238-dbba0e00-321f-11ea-928d-7cfcf08ffc1e.png)

**PDF Manual Sent**
![imagen](https://user-images.githubusercontent.com/51986864/71980634-d7dabb80-3220-11ea-8dc0-b305728c40f4.png)

## Your Environment

* Module version:
    - reporting: 0.10.0
* Dependent module versions:
    - IPL: 0.4.0
    - reactbundle: 0.7.0
    - pdfexport: 0.9.1
* Icinga Web 2 version and modules (System - About):
    - Icinga Web 2: 2.6.3
    - businessprocess: 2.2.0
    - director: 1.6.2
    - graphite: 1.1.0
    - idoreports: 0.9.1
    - monitoring: 2.6.3
* Web browser and version: 
    - Firefox: 70.0.1
* Icinga 2 version used (`icinga2 --version`):
    - Icinga 2: r2.10.5-1
* PHP version used (`php --version`):
    - PHP: 7.2.22
* Server operating system and version:
    - CentOS: 7.6.1810

## Additional context

**I have merged this branch and this patch of pdfexport module to work properly:**

https://github.com/Icinga/icingaweb2-module-pdfexport/tree/feature/enhance-export

https://gist.githubusercontent.com/durzo/e5e7db5fe8f54f4eaf7ad69260400bb9/raw/ef53b73a0b4194fe3bfa640b62070d412d383f91/patch.diff

**Comment by mariopatov** [comment]
Hello,

Thanks for logging this problem. Is there a patch that we can apply to resole it?

Mario

**Comment by cristorrian** [comment]
@mariopatov Not Actually, I'm still waiting for a patch that fix it.

**Comment by lippserd** [comment]
Hi,

I think that this is a problem with missing CSS because not all enabled modules are automatically loaded in CLI context. That has been fixed with Icinga Web version 2.7.0: https://github.com/Icinga/icingaweb2/pull/3852

Could you please upgrade Icinga Web and report back whether this fixes your issues?
The output of the schedule run command would also be nice.

All the best,
Eric

**Comment by mariopatov** [comment]
Hello,

In my case upgrading IcingaWeb2 from version 2.6.3 to 2.7.3 resolved this issue. For the upgrade itself, here is what I did on my CentOS7 server:

1. Make a backup of the IcingaWeb2 server. 
2. Create a repo file /etc/yum.repos.d/icinga-stable-release.repo with the following content:
[icinga-stable-release]
name=ICINGA (stable release for epel)
baseurl=http://packages.icinga.com/epel/$releasever/release/
enabled=1
gpgcheck=1
gpgkey=https://packages.icinga.com/icinga.key

2. To update to ICINGAWEB2 v2.7.3 from v2.6.3 :
yum install https://packages.icinga.com/epel/7Server/release/noarch/icingaweb2/icingaweb2-2.7.3-1.el7.icinga.noarch.rpm

3. Any customization on the CSS files should be re-applied.

Thank you,
Mario

**Comment by domme0711** [comment]
I have the same issue with icingaweb2-module-reporting v0.9.2 and icingaweb2 v2.9.3 (also with v2.9.5). 

Manually downloaded or mailed PDF includes styles and colors.
The PDF sent by the scheduler is plain text only.

The log shows the folling error, pointig to the less compiler:
`icingacli[32277]: ErrorException in /usr/share/php/Icinga/Web/LessCompiler.php:209 with message: file_get_contents(): Filename cannot be empty`

**Environment:**
SLES			15 SP2
PHP 			7.4.6
Icingaweb2 		2.9.3 (also 2.9.5)
icinga-php-library 	0.7.0
icinga-php-thirdparty 	0.10.0 
idoreports 		0.9.1
pdfexport 		0.9.1
reporting 		0.9.2
chromium		89.0.4389.128

Has anyone an idea how to fix this?

**Comment by nilmerg** [comment]
@domme0711 This is an issue with Icinga Web 2 v2.9.x. It has been addressed in https://github.com/Icinga/icingaweb2/pull/4636.

**Comment by nilmerg** [comment]
The next update will require Icinga Web 2 v2.7 at a minimum, so I consider this solved.
