### ISSUE TITLE
Can't create template: Call to undefined method getValue()

### ISSUE THREAD

**Issue by Quentinvarquet** [Icinga/icingaweb2-module-reporting#49]
## Describe the bug
Hello,

I am not able to create a template for my reports. For now I can only create a "system" reports

I got this error all the time : 

```
Uncaught Error: Call to undefined method Icinga\Module\Reporting\Web\Forms\TemplateForm::getValue() in /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Forms/TemplateForm.php:243
Stack trace:
#0 /usr/share/icingaweb2/modules/reporting/library/Reporting/Web/Forms/TemplateForm.php(109): Icinga\Module\Reporting\Web\Forms\TemplateForm->addColumnSettings('header_column1', 'Column 1')
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(256): Icinga\Module\Reporting\Web\Forms\TemplateForm->assemble()
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/Form.php(55): ipl\Html\HtmlDocument->ensureAssembled()
#3 /usr/share/icingaweb2/modules/reporting/application/controllers/TemplatesController.php(84): ipl\Html\Form->handleRequest(Object(GuzzleHttp\Psr7\ServerRequest))
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\TemplatesController->newAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Control

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

## To Reproduce

On icingaweb2 interface 

1. Reporting 
2. Open reports
3. Templates 
4. New template

## Expected behavior

I would like to be able to create a template ! 

## Screenshots

![image](https://user-images.githubusercontent.com/7962157/73934691-402fc200-48df-11ea-908b-cb62f03dbe5b.png)

## Your Environment

* Module version: 0.10.0
* Dependent module versions: ipl v0.2.1 / pdfexport 0.9.1 / reactbundle 0.0.0 (??)
* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser and version: latest version of chrome
* Icinga 2 version used (`icinga2 --version`): 2.11.2-1
* PHP version used (`php --version`): 5.4
* Server operating system and version: Centos 7.7 (kernel 3.10.0-1062)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I think that this is a dependency issue. Could you please upgrade the `ipl` module and report back whether this fixes your issue?

All the best,
Eric

**Comment by Quentinvarquet** [comment]
Hello. 

I did the upgrade. So right now  I have : 

- IPL : 0.5
- PDFEXPORT : 0.9.1
- Reporting : 0.9.2
- Reactbundle : 0.7

I dont have any error but... I dont have the option to create a template anymore. I only have system 

![image](https://user-images.githubusercontent.com/7962157/79269420-b7b03d80-7e9c-11ea-94bb-39336cbc828c.png)

![image](https://user-images.githubusercontent.com/7962157/79269510-df070a80-7e9c-11ea-8f24-cd4a83b57c4d.png)


Any idea ? :)

**Comment by Quentinvarquet** [comment]
My bad, I downgraded the version the model reporting by mystake...

So it's working after the upgrade of IPL ! :) 

Thank you
