### ISSUE TITLE
Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by Spicyq** [Icinga/icingaweb2-module-reporting#59]
## Describe the bug

After installing **icingaweb2-module-reporting** module (commit `4530809474c30ab5fd37558658d91d5e9aab1ffb`) and it's requirements this is what I see in `Reporting` -> `Reports` tab:
```
#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(309): PDO->prepare(String)
#1 /usr/share/icingaweb2/modules/reporting/library/Reporting/RetryConnection.php(13): ipl\Sql\Connection->prepexec(String, Array)
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(326): Icinga\Module\Reporting\RetryConnection->prepexec(String, Array)
#3 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php(41): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->indexAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#10 {main}
```
I've also tried using earlier versions of some modules, but no use.

## Screenshots

![Screenshot from 2020-04-14 18-51-00](https://user-images.githubusercontent.com/11815358/79245701-1e276280-7e81-11ea-87e7-bda7c40b7513.png)

## Your Environment

* Module version: 0.10.0
* Dependent module versions: 
  - ipl: v0.5.0
  - pdfexport: 0.9.1
  - reactbundle: v0.6.0
* Icinga Web 2 version and modules (System - About):
  - Icinga Web 2 Version: 2.7.3
  - Git commit: 06cabfe8ba28cf545a42c92f25484383191a4e51
  - PHP Version: 7.2.24-0ubuntu0.18.04.3
  - modules:

Name | Version
-- | --
cube | 1.1.0
grafana | 1.3.6
idoreports | 0.9.1
ipl | v0.5.0
monitoring | 2.7.3
pdfexport | 0.9.1
reactbundle | v0.6.0
reporting | 0.10.0

* Web browser and version: 
Mozilla Firefox for Ubuntu Version 75.0 (64-bit)
* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)
```
* PHP version used (`php --version`):
```
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
```
* Server operating system and version:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```
* MySQL version:
```
mysql  Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)
```
## Additional context

Icingaweb2 resource for `reporting` database:
```
...
[reporting_db]
type = "db"
db = "mysql"
host = "localhost"
port = "3306"
db_name = "reporting"
username = "reporting"
password = "mypassword"
charset = "utf8mb4"
persistent = "0"
use_ssl = "0"
```
Backend for reporting module:
Database -> `reporting_db`

**Comment by lippserd** [comment]
Hi,

It should be `dbname` instead of `db_name` in your resource configuration.

All the best,
Eric
