### ISSUE TITLE
% Sign in Report Name lead to an Error

### ISSUE THREAD

**Issue by mjeheuer** [Icinga/icingaweb2-module-reporting#62]
It is not possible to create a new report with the "%" sign in the name.

For Example:
The Name "Service <100% in 25Hours" for a new Report (or rename an existing Report)
will lead to an Error.
Editing or Modifing the Report is also not possible any more.

You have to delete the Report in the Database itselv.

**Comment by nilmerg** [comment]
Hi, thanks for the report. Can you please also add the exact error message and traceback?

**Comment by mjeheuer** [comment]
I created the Report with the following Points:

Name:         "Service <100% in 25Std"
Timeframe:  25 Hours
Report:        Service SLA
Filter:           -
Breakdown: None
Threshold:   99.9

After calling the Report I get the following Error:

vsprintf(): Too few arguments

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/reporting/library/vendor/ipl/web/src/Compat/CompatController.php(67): vsprintf(String, Array)
#2 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(36): reportingipl\Web\Compat\CompatController->setTitle(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}


Greetings
Michael

**Comment by mjeheuer** [comment]
Without % characters in the name there is no error message

**Comment by nilmerg** [comment]
Fixed since #104
