### ISSUE TITLE
Report Download (export) is missing Total (aggregated) SLA value

### ISSUE THREAD

**Issue by Napsty** [Icinga/icingaweb2-module-reporting#65]
## Is your feature request related to a problem? Please describe.
When checking a group of services, a Total value is generated at the end:

![image](https://user-images.githubusercontent.com/3702203/83722447-48a1ca80-a63d-11ea-9d12-7223053cba34.png)

However when the same report is downloaded/exported in another method (PDF, json or csv), the Total value is missing. Example here with json:

```
[{"Hostname":"inf-lxc01-p","Service Name":"CPU Load","SLA in %":36.8861},{"Hostname":"inf-mon02-t","Service Name":"CPU Load","SLA in %":37.5245},{"Hostname":"inf-mon03-t","Service Name":"CPU Load","SLA in %":42.3363},{"Hostname":"ver-adflapp02-p","Service Name":"CPU Load","SLA in %":100},{"Hostname":"ver-adflapp02-s","Service Name":"CPU Load","SLA in %":100},{"Hostname":"ver-adfldb02-p","Service Name":"CPU Load","SLA in %":100},{"Hostname":"ver-adfldb02-s","Service Name":"CPU Load","SLA in %":100}]
```

## Describe the solution you'd like
Add the total value in the PDF, json and csv exports.

**Comment by nilmerg** [comment]
In a PDF export it's there, at least now. If you export to CSV or JSON, you'll get the raw data. If you want the total (or rather average) uptime, calculate it with the program you feed the export to. (e.g. Excel if CSV)
