### ISSUE TITLE
service sla is red 0% but service is of downtime?

### ISSUE THREAD

**Issue by KBfly** [Icinga/icingaweb2-module-reporting#66]
Hello,

many thank's for the report module for icinga. 
we want's to use this module for kpis now.

but i think this is not correct:
a service or a host ist set of downtime.
if i create a report of this service or host so the sla is red and sla% is 0. (of course, it is not available, but it is of  a planned downtime) 
-> i think if a service (or host) is set of downtime, so it should not be included as a fault or 0% in the report?

best regards 
Karsten

**Comment by yhabteab** [comment]
Hii @KBfly, thanks for the report and sorry for the late response.

If that’s still the case, can you please provide step by step instructions here on how I can reproduce the issue. Like how you created the reports that led to this result.

**Comment by yhabteab** [comment]
I wasn't able to reproduce this issue, nor was I able to get any updates from OP. So I am going to close this.
