### ISSUE TITLE
CSV Filename

### ISSUE THREAD

**Issue by ohdearaugustin** [Icinga/icingaweb2-module-reporting#67]
## Describe the bug

The CSV file naming is not working correctly when there is a space in the report name. Furthermore no file extension is added. (.csv)

## To Reproduce

Steps to reproduce the behaviour:

1. Create a report named "Single Instance" or named anything with a space in it.
2. Download the report as CSV
3. Check the downloaded filename

## Expected behaviour

The file should be named single_instance.csv or Single Instance.csv

## Your Environment

* Module version: 0.9.2
* Dependent module versions: 
* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser and version: Firefox 77.0.1 (64-bit)
* Icinga 2 version used (`icinga2 --version`): 2.11.2-1
* PHP version used (`php --version`): php 7.1
* Server operating system and version: Redhat 7

**Comment by nilmerg** [comment]
Works for me, with v0.9.2 and on the current master.
