### ISSUE TITLE
icinga-reporting.service - Icinga Reporting Scheduler -> Daemon failed

### ISSUE THREAD

**Issue by KBfly** [Icinga/icingaweb2-module-reporting#69]
i have created some reports and set on various time scheduler.

icingacli reporting schedule run
systemctl start icinga-reporting.service
systemctl enable icinga-reporting.service
...
but after the time for one scheduler is running the daemon is failed.
-> start deamon again (one time it works for 2 reports) -> but after that deamon is dead!

 ERROR: Exception in /usr/share/icingaweb2/modules/pdfexport/library/Pdfe...ails.
systemd[1]: icinga-reporting.service: main process exited, code=exited, status=1/FAILURE
Unit icinga-reporting.service entered failed state.
icinga-reporting.service failed.

---------------------------------------------------------------
MODULE         VERSION   STATE     DESCRIPTION
idoreports     0.9.1     enabled   Reports for IDO
incubator      0.5.0     enabled   Incubator provides bleeding-edge libraries
ipl            v0.5.0    enabled   The Icinga PHP library
monitoring     2.7.3     enabled   Icinga monitoring module
pdfexport      0.9.1     enabled   PDF Export via Google Chrome/Chromium
reactbundle    0.7.0     enabled   ReactPHP-based 3rd party libraries
reporting      0.9.2     enabled   Reporting

----------------------------------------------------------------------------------
next test:
1 report is probaly working with time scheduler . But more then 1 report daemon crashed and failed.
----------------------------------------------------------------------------------

Jul 01 11:03:48  icingacli[10100]: Scheduling job Schedule 21 to run at 2020-07-01 11:14:00.
Jul 01 11:03:48  icingacli[10100]: Scheduling job Schedule 23 to run at 2020-07-01 11:12:00.
Jul 01 11:04:48  icingacli[10100]: Scheduling job Schedule 25 to run at 2020-07-01 11:10:00.
Jul 01 11:05:48  icingacli[10100]: Scheduling job Schedule 27 to run at 2020-07-01 11:15:00.
Jul 01 11:10:02  ingacli[10100]: Scheduling job Schedule 25 to run at 2020-08-01 11:10:02.
Jul 01 11:12:11 icingacli[10100]: Terminated browser process after 10 seconds elapsed without the expected output
Jul 01 11:12:11 icingacli[10100]: ERROR: Exception in /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/Headless...etails.
Jul 01 11:12:11 systemd[1]: icinga-reporting.service: main process exited, code=exited, status=1/FAILURE
Jul 01 11:12:11 systemd[1]: Unit icinga-reporting.service entered failed state.
Jul 01 11:12:11 systemd[1]: icinga-reporting.service failed.

->
what's wrong?

regards,
Karsten

**Comment by bobapple** [comment]
ref/NC/682655

**Comment by KBfly** [comment]
? ... sorry, please couldt you write in whole sentences.

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by KBfly** [comment]
**work around this problem:**
-------------------------------------

1. create a folder /etc/systemd/system/icinga- reporting.service.d
2. create into this folder a file restart.conf 
3. edit the file: 
   [Service]
   Restart=always

  ... and save the file
4. systemctl daemon-reload
5. systemctl restart icinga- reporting.service

Not nice, but it works!

**Comment by yhabteab** [comment]
I am unable to reproduce this. If you still have this problem with the latest release, please reopen this and provide a detailed instruction on how to reproduce it.

```bash
root@61365c992770:/var/www/html# icingacli reporting schedule run
Scheduling job Schedule 1 to run at 2023-01-25 10:14:52.
Jan 25 09:14:57 from=reporting@icinga recipients=yonas.habteab@netways.de mailsize=52748 54876 bytes in 0.138, 387,164 KB/sec Queued mail for delivery' exitcode=EX_OK
Scheduling job Schedule 1 to run at 2023-01-25 10:15:52.
Jan 25 09:15:56 from=reporting@icinga recipients=yonas.habteab@netways.de mailsize=52748 54876 bytes in 0.138, 387,164 KB/sec Queued mail for delivery' exitcode=EX_OK
Scheduling job Schedule 1 to run at 2023-01-25 10:16:52.
Jan 25 09:16:58 from=reporting@icinga recipients=yonas.habteab@netways.de mailsize=52748 54876 bytes in 0.154, 347,379 KB/sec Queued mail for delivery' exitcode=EX_OK
Scheduling job Schedule 1 to run at 2023-01-25 10:17:52.
```
