### ISSUE TITLE
Error - Page Not Found

### ISSUE THREAD

**Issue by superfunkie** [Icinga/icingaweb2-module-reporting#82]
Hello,

I've recently installed icingaweb2 reporting module by following instructions given on the readme page.

Module has been activated but when I try to generate reports, I get page not found error on the dashboard. Same error I get when I try to configure the backend on modules section.

Please advise.

Log errors.

```
2021-01-06T04:36:31-05:00 - ERROR - Zend_Controller_Dispatcher_Exception in /usr/local/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php:358 with message: Invalid controller class ("Icingaweb2ModuleReporting092_ConfigController")
2021-01-06T04:36:31-05:00 - ERROR - Stacktrace: #0 /usr/local/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(271): Zend_Controller_Dispatcher_Standard->loadClass('ConfigControlle...')
#1 /usr/local/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#2 /usr/local/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/local/icingaweb2/library/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/local/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#5 /usr/local/icingaweb2/public/index.php(4): require_once('/usr/local/icin...')
#6 {main}
```

**Comment by nilmerg** [comment]
Hi,

you seem to have edited the file `application/controllers/ConfigController` and renamed the class in there. (Or something did that what you've used to install the module) Just remove the prefix `Icingaweb2ModuleReporting092_` and this error is gone.

Next time, please mark stacktraces as code sections!

**Comment by superfunkie** [comment]
I havent edited any file. Just installed the module as per the given instructions. There is no prefix with that name in the file.

When clicking on reports getting this error.

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /usr/local/icingaweb2/modules/reporting/library/vendor/ipl/web/src/Compat/CompatController.php on line 65

It is also breaking the entire portal.

Pls advise.

**Comment by nilmerg** [comment]
Huh? Please don't tell me you're using PHP 8 then. If so, that's the weirdest error message I've seen from that yet. (The one in the OP)

The second error seems more familiar to me regarding PHP version incompatibilities. Make sure you're running a version supported by Icinga Web 2. (PHP 5.6 to PHP 7.4)

**Comment by superfunkie** [comment]
Current PHP version running.

PHP 5.6.40 (cli) (built: Sep 29 2020 11:19:06)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

Still getting the same error. Anywhere else to look?

**Comment by nilmerg** [comment]
This is, still very strange. Didn't take a closer look earlier, but the error message complains about a feature that's been introduced with PHP 5.6. That shouldn't be a problem, because you're running PHP 5.6.

If installed by our packages, Icinga Web 2 will run under php-fpm (on CentOS and Redhat). Is there maybe another php version active for php-fpm? Or some other fpm implementation you're using? Some non-standard php module you've installed?
