### ISSUE TITLE
Error while starting the reporting Module

### ISSUE THREAD

**Issue by pranavrn** [Icinga/icingaweb2-module-reporting#99]
Hi Team,

Sorry I'm not sure whether I'm posting here is right place or not but can anyone please help me out of this issue. I'm new on this tool

I'm trying to installing the reporting module and I followed the below document link. But unfortunately when I tried to start the reporting service getting the below error. Can any one help me or provide me some good document to install reporting module properly.

https://icinga.com/docs/icinga-reporting/latest/doc/02-Installation/

**icingacli module enable reporting
ERROR: Icinga\Exception\ConfigurationError in /usr/share/php/Icinga/Application/Modules/Manager.php:253 with message: Cannot enable module "reporting". Module is not installed.**

Regards,
Pranav R N

**Comment by nilmerg** [comment]
Hi,

you already have a discussion for this [on the forums](https://community.icinga.com/t/unable-to-install-the-icinga-report-module/8104). Please try to solve your problem there.

Thanks
